#!/bin/bash

if [ -z "$GOPATH" ]
then
	echo "\$GOPATH is empty"
else
	echo "Deactivating : \$GOPATH -> $GOPATH"
	unset GOPATH
fi
if [ -z "$LGDIR" ]
then
	echo "\$LGDIR is empty"
else
	unset LGDIR
fi
source $HOME/.bashrc
